config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resource :cart, only: [:show] do
    post 'add_item', on: :member
    get 'pay', on: :member
    post 'process_payment', on: :member
    delete 'remove_item', on: :member
    delete 'delete_item', on: :member
  end

  resources :orders, only: [:index]

  # Defines the root path route ("/")
  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # before_action :authenticate_user!

  def index
    if params[:query].present?
      @products = Product.where("name LIKE #{params[:query]} OR description LIKE #{params[:query]}")
    else
      @products = Product.all
    end
  end
end

app/views/home/index.erb
<h1 class="text-center my-4">Bem vindo ao ecommerce!</h1>

<%= form_with url: root_path, method: :get, local: true do %>
  <div class="input-group mb-3">
    <input type="text" name="query" class="form-control" placeholder="Buscar produtos por nome ou descrição" value="<%= params[:query] %>">
    <div class="input-group-append">
      <button class="btn btn-outline-secondary" type="submit">Buscar</button>
    </div>
  </div>
<% end %>

<h2 class="text-center my-4">Products</h2>

<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-3 mb-4">
      <div class="card">
        <img src="<%= product.image %>" class="card-img-top" alt="<%= product.name %>">
        <div class="card-body">
            <h5 class="card-title"><%= link_to product.name, product_path(product) %></h5>
            <%= button_to 'Adicionar ao carrinho', add_item_cart_path(item: product.id), method: :post, class: "btn btn-primary" %>
          <p class="card-text"><%= number_to_currency(product.price) %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>