config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resource :cart, only: [:show] do
    post 'add_item', on: :member
    get 'pay', on: :member
    post 'process_payment', on: :member
    delete 'remove_item', on: :member
    delete 'delete_item', on: :member
  end

  resources :orders, only: [:index]

  # Defines the root path route ("/")
  root to: "home#index"
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  protect_from_forgery except: :process_payment

  def show
    @cart = cart_products || []
    @total = calculate_total(@cart)
  end

  def add_item
    session[:cart] ||= {}
    if Product.exists?(params[:item])
      product = Product.find(params[:item])
      if product.stock > session[:cart][params[:item]].to_i
        session[:cart][params[:item]] ||= 0
        session[:cart][params[:item]] += 1
        notice = "Item adicionado ao carrinho."
      else
        notice = "Estoque insuficiente para adicionar mais deste item."
      end
    else
      notice = "Item não encontrado."
    end
    redirect_back(fallback_location: root_path, notice: notice)
  end

  def remove_item
    session[:cart] ||= {}
    if session[:cart][params[:item]].to_i > 0
      session[:cart][params[:item]] -= 1
      session[:cart].delete(params[:item]) if session[:cart][params[:item]] <= 0
      notice = "Item removido do carrinho."
    else
      notice = "Item não encontrado no carrinho."
    end
    redirect_to cart_path, notice: notice
  end

  def delete_item
    session[:cart] ||= {}
    if session[:cart].delete(params[:item])
      notice = "Todos os itens do tipo foram removidos do carrinho."
    else
      notice = "Item não encontrado no carrinho."
    end
    redirect_to cart_path, notice: notice
  end

  def pay
    require 'mercadopago'

    @cart = cart_products || []
    @total = calculate_total(@cart)
    if @cart.empty?
      redirect_to cart_path, alert: "Seu carrinho está vazio."
    else
      render :pay
    end
  end

  def process_payment
    require 'mercadopago'

    # Integração com Mercado Pago
    sdk = Mercadopago::SDK.new('TEST-6597116855860817-021309-046d3a9de12461f3a02bde0bcd24bd60-278204658')
    
    payment_data = {
      transaction_amount: params[:transaction_amount].to_f,
      token: params[:token],
      installments: params[:installments].to_i,
      payment_method_id: params[:payment_method_id],
      payer: {
        email: params[:payer][:email],
        identification: {
          type: params[:payer][:identification][:type],
          number: params[:payer][:identification][:number]
        },
      }
    }

    payment_response = sdk.payment.create(payment_data)
    payment = payment_response[:response]
    
    if payment['status'] == 'approved'
      create_order payment_data[:transaction_amount]
      clear_cart
      render json: { success: true, message: "Pagamento realizado com sucesso." }
    else
      render json: { success: false, message: "Falha no pagamento" }
    end
  end

  private

  def calculate_total(cart)
    cart.sum { |product| product.price * session[:cart][product.id.to_s].to_i }
  end

  def cart_products
    product_ids = session[:cart].keys || []
    existing_products = Product.where(:_id.in => product_ids)
    session[:cart].slice!(*existing_products.pluck(:id).map(&:to_s)) # atualiza a sessão com apenas os produtos existentes
    existing_products
  end

  def clear_cart
    product_counts = session[:cart] || {}
    products = Product.where(:_id.in => product_counts.keys)
    products.each do |product|
      count = product_counts[product.id.to_s] || 0
      product.update(stock: product.stock - count)
    end
    session[:cart] = {}
  end

  def create_order total_price
    order = Order.new(
      user: current_user,
      total_price: total_price,
      products: session[:cart].map do |product_id, quantity|
        { product_id: product_id, quantity: quantity }
      end
    )
    success = order.save!
    end
end

app/views/carts/pay.html.erb
<div id="cardPaymentBrick_container"></div>
<script>
  const mp = new MercadoPago('TEST-b127b56a-0e54-4a77-bbcf-111785e6bf92', {
    locale: 'pt-BR'
  });
  const bricksBuilder = mp.bricks();
  const renderCardPaymentBrick = async (bricksBuilder) => {
    const settings = {
      initialization: {
        amount: <%= @total %>, // valor total a ser pago
        payer: {
          email: "<%= current_user ? current_user.email : '' %>",
        },
      },
      customization: {
        visual: {
          style: {
            theme: 'bootstrap', // | 'dark' | 'bootstrap' | 'flat'
            customVariables: {
            }
          }
        },
          paymentMethods: {
            types: {
              excluded: ['debit_card']
            }, 
            maxInstallments: 1,
          }
      },
      callbacks: {
        onReady: () => {
          // callback chamado quando o Brick estiver pronto
        },
        onSubmit: (cardFormData) => {
          //  callback chamado o usuário clicar no botão de submissão dos dados
          //  exemplo de envio dos dados coletados pelo Brick para seu servidor
          return new Promise((resolve, reject) => {
            fetch("<%= process_payment_cart_path %>", {
              method: "POST",
              headers: {
              "Content-Type": "application/json",
              },
              body: JSON.stringify(cardFormData)
            })
              .then((response) => response.json())
              .then((data) => {
              console.log(data);
              alert(data.message);
                if (data.success) {
                  window.location.href = "<%= root_path %>";
                } else {
                  alert(data.message);
                  window.location.href = "<%= cart_path %>";
                }
                resolve();
              })
              .catch((error) => {
                // lidar com a resposta de erro ao tentar criar o pagamento
                console.error(error);
                alert("Erro ao processar pagamento.");
                reject();
              })
          });
        },
        onError: (error) => {
          // callback chamado para todos os casos de erro do Brick
        },
      },
    };
    window.cardPaymentBrickController = await bricksBuilder.create('cardPayment', 'cardPaymentBrick_container', settings);
  };
  renderCardPaymentBrick(bricksBuilder);
</script>

app/views/carts/show.html.erb
<h1 class="text-center my-4">Seu Carrinho</h1>
<ul class="list-group">
    <% @cart.each do |product| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="col-1">
            <img src="<%= product.image %>" class="card-img-top img-fluid" alt="<%= product.name %>">
          </div>
          <div class="col-6">
            <h5><%= product.name %></h5>
            <p><%= product.description %></p>
            <p>Preço: R$ <%= product.price %></p>
          </div>
          <div class="col-3 d-inline-flex justify-content-between align-items-center">
            <div class="d-inline-flex align-items-center">
              <%= button_to remove_item_cart_path(item: product.id), method: :delete, class: "btn btn-warning btn-sm mx-1" do %>
                <i class="bi bi-dash"></i>
              <% end %>
              <span class="mx-2"><%= session[:cart][product.id.to_s] %></span>
              <%= button_to add_item_cart_path(item: product.id), method: :post, class: "btn btn-success btn-sm mx-1" do %>
                <i class="bi bi-plus"></i>
              <% end %>
            </div>
            <%= button_to delete_item_cart_path(item: product.id), method: :delete, class: "btn btn-danger btn-sm ms-auto" do %>
              <i class="bi bi-trash"></i>
            <% end %>
          </div>
        </li>
    <% end %>
</ul>
<div class="row my-5">
<span>Total: R$ <%= @total %></span>
<%= link_to pay_cart_path, class: "btn btn-success mt-3" do %>
  <i class="bi bi-credit-card"></i> Pagar
<% end %>
</div>