config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resource :cart, only: [:show] do
    post 'add_item', on: :member
    get 'pay', on: :member
    post 'process_payment', on: :member
    delete 'remove_item', on: :member
    delete 'delete_item', on: :member
  end

  resources :orders, only: [:index]

  # Defines the root path route ("/")
  root to: "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <script src="https://sdk.mercadopago.com/js/v2"></script>
    <%= javascript_include_tag "application" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>

  <body>
    <nav class="navbar bg-primary mb-3" data-bs-theme="dark">
        <div class="container">
            <a class="navbar-brand" href="/">eCommerce</a>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex flex-row">
                <li class="nav-item me-3">
                <%= link_to "Produtos", products_path, class: "nav-link #{'active' if current_page?(products_path)}" %>
                </li>
                <li class="nav-item me-3">
                <%= link_to "Carrinho", cart_path, class: "nav-link #{'active' if current_page?(cart_path)}" %>
              </li>
            </ul>
            <p class="navbar-text ms-auto">
            <% if user_signed_in? %>
              <ul class="navbar-nav d-flex flex-row">
              <li class="nav-item me-3">
                Logged in as <strong><%= current_user.email %></strong>.
              </li>
              <li class="nav-item me-3">
                <%= link_to 'Ver pedidos', orders_path, :class => 'nav-link' %>
              </li>
              <li class="nav-item me-3">
                <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'nav-link' %>
              </li>
              <li class="nav-item me-3">
                <%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link' %>
              </li>
              </ul>
            <% else %>
              <ul class="navbar-nav d-flex flex-row">
              <li class="nav-item me-3">
                <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link' %>
              </li>
              <li class="nav-item me-3">
                <%= link_to "Login", new_user_session_path, :class => 'nav-link' %>
              </li>
              </ul>
            <% end %>
          </p>
        </div>
    </nav>
    <% if notice %>
      <div class="alert alert-success text-center mx-auto col-8" role="alert">
      <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger text-center mx-auto col-8" role="alert">
      <%= alert %>
      </div>
    <% end %>

    <div class="container mt-3">
      <%= yield %>
    </div>
  </body>
</html>